services:
  - type: web
    name: wanderlust-app
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
